export {default as Header} from './header'
export {default as DefaultHomepage} from './defaulthomepage'
export {default as AllGuitars} from './allguitars'
export {default as Login} from './login'
export {default as Register} from './register'