export { default as Header } from "./header";
export { default as DefaultHomepage } from "./defaulthomepage";
export { default as Login } from "./login";
export { default as Register } from "./register";
export { default as Products } from "./products";
export { default as Footer } from "./footer";
export { default as Cart } from "./cart";
export { default as CartItem } from "./cartitem";
export {default as SingleProduct} from './singleproduct';
export {default as ConfirmOrder} from './confirmorder';
